import api from '@/services/api.service';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// type Props = { children: ReactNode };

const CarLayout = (children: ReactNode) => {

  return (

    <div>
      car page
      {children}
    </div>
  );
};

export default CarLayout;
