import { MarkerEnum } from '../../repository/enums/marker.enum';
import { UserPlanEnum } from '../../users/enums/user-plan.enum';
import { AdminRoleEnum } from '../../users/enums/user-role.enum';
import { CurrencyEnum } from '../enums/currency.enum';

export interface ICarRawBase {
  car_id: string;
  car_created: Date;
  car_updated: Date;
  car_mileage: number;
  car_build: number;
  car_price: number;
  car_currency: CurrencyEnum;
  car_description: string;
  car_active: boolean;
  car_version: number;
  car_image: string[];
  car_userId: string;
  car_brandName: string;
  car_modelId: string;
  car_rateMarker: MarkerEnum;
  car_locationCity: string;
  rate_marker: MarkerEnum;
  rate_buy_eur: number;
  rate_sale_eur: number;
  rate_buy_usd: number;
  rate_sale_usd: number;
  rate_created: Date;
  rate_updated: Date;
  brand_name: string;
  model_id: string;
  model_created: Date;
  model_updated: Date;
  model_name: string;
  model_brandName: string;
  location_city: string;
  location_lat: string;
  location_lng: string;
  location_country: string;
  location_iso2: string;
  location_region: string;
  location_capital: string;
  user_id: string;
  user_created: Date;
  user_updated: Date;
  user_first_name: string;
  user_last_name: string;
  user_email: string;
  user_phone: string;
  user_role: AdminRoleEnum;
  user_plan: UserPlanEnum;
  user_verify: boolean;
  user_ban: boolean;
  user_avatar_image: string | null;
  car_price_calculated: number;
  car_currency_final: CurrencyEnum;
}
